In [89]:
import pandas as pd

In [90]:
city_day = pd.read_csv('city_day.csv')
crop_production = pd.read_csv('crop_production.csv')

### Task 1

In [91]:
city_day.shape

(29531, 16)

In [92]:
city_day.head()

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [93]:
city_day.info()

<class 'pandas.DataFrame'>
RangeIndex: 29531 entries, 0 to 29530
Data columns (total 16 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        29531 non-null  str
 1   Date        29531 non-null  str
 2   PM2.5       24933 non-null  float64
 3   PM10        18391 non-null  float64
 4   NO          25949 non-null  float64
 5   NO2         25946 non-null  float64
 6   NOx         25346 non-null  float64
 7   NH3         19203 non-null  float64
 8   CO          27472 non-null  float64
 9   SO2         25677 non-null  float64
 10  O3          25509 non-null  float64
 11  Benzene     23908 non-null  float64
 12  Toluene     21490 non-null  float64
 13  Xylene      11422 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  str
dtypes: float64(13), str(3)
memory usage: 4.3 MB

In [94]:
city_day.describe()

,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI
count,24933.000000,18391.000000,25949.000000,25946.000000,25346.000000,19203.000000,27472.000000,25677.000000,25509.000000,23908.000000,21490.000000,11422.000000,24850.000000
mean,67.450578,118.127103,17.574730,28.560659,32.309123,23.483476,2.248598,14.531977,34.491430,3.280840,8.700972,3.070128,166.463581
std,64.661449,90.605110,22.785846,24.474746,31.646011,25.684275,6.962884,18.133775,21.694928,15.811136,19.969164,6.323247,140.696585
min,0.040000,0.010000,0.020000,0.010000,0.000000,0.010000,0.000000,0.010000,0.010000,0.000000,0.000000,0.000000,13.000000
25%,28.820000,56.255000,5.630000,11.750000,12.820000,8.580000,0.510000,5.670000,18.860000,0.120000,0.600000,0.140000,81.000000
50%,48.570000,95.680000,9.890000,21.690000,23.520000,15.850000,0.890000,9.160000,30.840000,1.070000,2.970000,0.980000,118.000000
75%,80.590000,149.745000,19.950000,37.620000,40.127500,30.020000,1.450000,15.220000,45.570000,3.080000,9.150000,3.350000,208.000000
max,949.990000,1000.000000,390.680000,362.210000,467.630000,352.890000,175.810000,193.860000,257.730000,455.030000,454.850000,170.370000,2049.000000

In [95]:
city_day.isnull().sum()

City              0
Date              0
PM2.5          4598
PM10          11140
NO             3582
NO2            3585
NOx            4185
NH3           10328
CO             2059
SO2            3854
O3             4022
Benzene        5623
Toluene        8041
Xylene        18109
AQI            4681
AQI_Bucket     4681
dtype: int64

In [96]:
crop_production.shape

(246091, 7)

In [97]:
crop_production.head()

,State_Name,District_Name,Crop_Year,Season,Crop,Area,Production
0,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Arecanut,1254.0,2000.0
1,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Other Kharif pulses,2.0,1.0
2,Andaman and Nicobar Islands,NICOBARS,2000,Kharif,Rice,102.0,321.0
3,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Banana,176.0,641.0
4,Andaman and Nicobar Islands,NICOBARS,2000,Whole Year,Cashewnut,720.0,165.0

In [98]:
crop_production.info()

<class 'pandas.DataFrame'>
RangeIndex: 246091 entries, 0 to 246090
Data columns (total 7 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   State_Name     246091 non-null  str
 1   District_Name  246091 non-null  str
 2   Crop_Year      246091 non-null  int64
 3   Season         246091 non-null  str
 4   Crop           246091 non-null  str
 5   Area           246091 non-null  float64
 6   Production     242361 non-null  float64
dtypes: float64(2), int64(1), str(4)
memory usage: 22.0 MB

In [99]:
crop_production.describe()

           Crop_Year          Area    Production
count  246091.000000  2.460910e+05  2.423610e+05
mean     2005.643018  1.200282e+04  5.825034e+05
std         4.952164  5.052340e+04  1.706581e+07
min      1997.000000  4.000000e-02  0.000000e+00
25%      2002.000000  8.000000e+01  8.800000e+01
50%      2006.000000  5.820000e+02  7.290000e+02
75%      2010.000000  4.392000e+03  7.023000e+03
max      2015.000000  8.580100e+06  1.250800e+09

In [100]:
crop_production.isnull().sum()

State_Name          0
District_Name       0
Crop_Year           0
Season              0
Crop                0
Area                0
Production       3730
dtype: int64

# Task 2

In [101]:
# AQI and AQI_Bucket are the mostly the target variables for this project. It doesn't make sense to to have rows without their target value. 

city_day_clean = city_day.dropna(subset = ['AQI', 'AQI_Bucket']).copy()

In [102]:
# Filling the pollutant columns with the median value for each city.

pollutant_cols = ['PM2.5', 'PM10', 'NO', 'NO2', 'NOx', 'NH3', 'CO', 'SO2', 'O3', 'Benzene', 'Toluene', 'Xylene']

city_day_clean[pollutant_cols] = (city_day_clean.groupby('City')[pollutant_cols].transform(lambda x: x.fillna(x.median())))

In [103]:
# There might still be missing values, so filling them with the overall median for each pollutant.

city_day_clean[pollutant_cols] = city_day_clean[pollutant_cols].fillna(city_day_clean[pollutant_cols].median())

In [104]:
city_day_clean.isnull().sum()

City          0
Date          0
PM2.5         0
PM10          0
NO            0
NO2           0
NOx           0
NH3           0
CO            0
SO2           0
O3            0
Benzene       0
Toluene       0
Xylene        0
AQI           0
AQI_Bucket    0
dtype: int64

For the pollutant columns, I filled the missing values with the city-wise median, as the dataset in general, has a lot of outliers. Using the mean, implies that every value is used directly, so a few large values can distort it.

The median represents the typical value because it is the middle value after sorting.

In [105]:
crop_production_clean = crop_production.copy()

crop_production_clean['Production'] = (crop_production_clean.groupby(['State_Name', 'Crop'])['Production'].transform(lambda x: x.fillna(x.median())))

In [106]:
crop_production_clean['Production'] = (crop_production_clean.groupby('Crop')['Production'].transform(lambda x: x.fillna(x.median())))

In [107]:
crop_production_clean.isnull().sum()

State_Name       0
District_Name    0
Crop_Year        0
Season           0
Crop             0
Area             0
Production       0
dtype: int64

I filled the Production column with median values again, because the values seem to be extreme.

# Task 3

In [108]:
city_day_clean['City'].unique()

<ArrowStringArray>
[         'Ahmedabad',             'Aizawl',          'Amaravati',
           'Amritsar',          'Bengaluru',             'Bhopal',
       'Brajrajnagar',         'Chandigarh',            'Chennai',
         'Coimbatore',              'Delhi',          'Ernakulam',
           'Gurugram',           'Guwahati',          'Hyderabad',
             'Jaipur',         'Jorapokhar',              'Kochi',
            'Kolkata',            'Lucknow',             'Mumbai',
              'Patna',           'Shillong',            'Talcher',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 26, dtype: str

In [109]:
crop_production_clean['State_Name'].unique()

<ArrowStringArray>
['Andaman and Nicobar Islands',              'Andhra Pradesh',
           'Arunachal Pradesh',                       'Assam',
                       'Bihar',                  'Chandigarh',
                'Chhattisgarh',      'Dadra and Nagar Haveli',
                         'Goa',                     'Gujarat',
                     'Haryana',            'Himachal Pradesh',
          'Jammu and Kashmir ',                   'Jharkhand',
                   'Karnataka',                      'Kerala',
              'Madhya Pradesh',                 'Maharashtra',
                     'Manipur',                   'Meghalaya',
                     'Mizoram',                    'Nagaland',
                      'Odisha',                  'Puducherry',
                      'Punjab',                   'Rajasthan',
                      'Sikkim',                  'Tamil Nadu',
                  'Telangana ',                     'Tripura',
               'Uttar Pradesh',                 'Uttarakhand',
                 'West Bengal']
Length: 33, dtype: str

In [110]:
city_to_state = {
    'Ahmedabad': 'Gujarat',
    'Aizawl': 'Mizoram',
    'Amaravati': 'Andhra Pradesh',
    'Amritsar': 'Punjab',
    'Bengaluru': 'Karnataka',
    'Bhopal': 'Madhya Pradesh',
    'Brajrajnagar': 'Odisha',
    'Chandigarh': 'Chandigarh',
    'Chennai': 'Tamil Nadu',
    'Coimbatore': 'Tamil Nadu',
    'Delhi': 'Delhi',
    'Ernakulam': 'Kerala',
    'Gurugram': 'Haryana',
    'Guwahati': 'Assam',
    'Hyderabad': 'Telangana',
    'Jaipur': 'Rajasthan',
    'Jorapokhar': 'Jharkhand',
    'Kochi': 'Kerala',
    'Kolkata': 'West Bengal',
    'Lucknow': 'Uttar Pradesh',
    'Mumbai': 'Maharashtra',
    'Patna': 'Bihar',
    'Shillong': 'Meghalaya',
    'Talcher': 'Odisha',
    'Thiruvananthapuram': 'Kerala',
    'Visakhapatnam': 'Andhra Pradesh'
}

city_day_clean['State_Name'] = city_day_clean['City'].map(city_to_state)

In [111]:
city_day_clean.info()

<class 'pandas.DataFrame'>
Index: 24850 entries, 28 to 29530
Data columns (total 17 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   City        24850 non-null  str
 1   Date        24850 non-null  str
 2   PM2.5       24850 non-null  float64
 3   PM10        24850 non-null  float64
 4   NO          24850 non-null  float64
 5   NO2         24850 non-null  float64
 6   NOx         24850 non-null  float64
 7   NH3         24850 non-null  float64
 8   CO          24850 non-null  float64
 9   SO2         24850 non-null  float64
 10  O3          24850 non-null  float64
 11  Benzene     24850 non-null  float64
 12  Toluene     24850 non-null  float64
 13  Xylene      24850 non-null  float64
 14  AQI         24850 non-null  float64
 15  AQI_Bucket  24850 non-null  str
 16  State_Name  24850 non-null  str
dtypes: float64(13), str(4)
memory usage: 4.3 MB

In [113]:
print("Original rows:", len(crop_production_clean))
print("Exact duplicate rows:", crop_production_clean.duplicated().sum())

Original rows: 246091
Exact duplicate rows: 0

In [114]:
key_cols = ['State_Name', 'District_Name', 'Crop_Year', 'Season', 'Crop']
dup_key = crop_production_clean.duplicated(subset=key_cols, keep=False)

print("Rows with duplicate keys:", dup_key.sum())

Rows with duplicate keys: 0

In [115]:
dup_summary = (
    crop_production_clean
    .groupby(key_cols)
    .size()
    .reset_index(name='count')
    .query('count > 1')
)
dup_summary

Empty DataFrame
Columns: [State_Name, District_Name, Crop_Year, Season, Crop, count]
Index: []

In [116]:
print("city_day_clean exact duplicates:", city_day_clean.duplicated().sum())

city_day_clean exact duplicates: 0

In [118]:
city_key_cols = ['City', 'Date']
dup_city = city_day_clean.duplicated(subset=city_key_cols, keep=False)
print("city_day_clean duplicate City+Date rows:", dup_city.sum())

city_day_clean duplicate City+Date rows: 0